-- Número de competiciones por temporada - debería ser creciente
SELECT SEASON, COUNT(*) FROM COMPETITION GROUP BY SEASON ORDER BY SEASON

-- Listado de toda la nomenclatura de fases
SELECT DISTINCT NAME FROM PHASE;

SELECT COMPETITION.NAME, COMPETITION.SEASON, PHASE.NAME 
FROM PHASE JOIN COMPETITION ON PHASE.COMPETITION = COMPETITION.ID 
WHERE PHASE.NAME = 'Qualifying Phase';

-- Listado de fases disponibles por competicion
SELECT COMPETITION.NAME, COMPETITION.SEASON, COUNT(PHASE.NAME) 
FROM PHASE JOIN COMPETITION ON PHASE.COMPETITION = COMPETITION.ID
GROUP BY COMPETITION.NAME, COMPETITION.SEASON 
ORDER BY COMPETITION.NAME, COMPETITION.SEASON

-- Numero máximo/mínimo de rondas extraidas para cada competicion
SELECT A.NAME COMPETITION, MAX(A.NUM) MAX_PHASES, MIN(A.NUM) MIN_PHASES
FROM
(
SELECT COMPETITION.NAME, COMPETITION.SEASON, COUNT(PHASE.NAME) NUM 
FROM PHASE JOIN COMPETITION ON PHASE.COMPETITION = COMPETITION.ID
GROUP BY COMPETITION.NAME, COMPETITION.SEASON 
) A
GROUP BY A.NAME;

SELECT COMPETITION.NAME, COMPETITION.SEASON, COUNT(PHASE.NAME) NUM 
FROM PHASE JOIN COMPETITION ON PHASE.COMPETITION = COMPETITION.ID
GROUP BY COMPETITION.NAME, COMPETITION.SEASON 
ORDER BY NUM ASC


SELECT COMPETITION.NAME, COMPETITION.SEASON, PHASE.NAME 
FROM PHASE JOIN COMPETITION ON PHASE.COMPETITION = COMPETITION.ID
WHERE COMPETITION.NAME LIKE 'Champions%' AND COMPETITION.SEASON ='1997-98'



-- Eliminatorias a dos extraidas por competicion 
SELECT MATCH_PAIR.COMPETITION, COUNT(*) 
FROM MATCH_PAIR 
GROUP BY MATCH_PAIR.COMPETITION;

SELECT COUNT(*) 
FROM MATCH_PAIR 


SELECT MAX(NUM), MIN(NUM), AVG(NUM)
FROM 
(
SELECT MATCH_PAIR.COMPETITION, COUNT(*) NUM
FROM MATCH_PAIR 
GROUP BY MATCH_PAIR.COMPETITION
) AS A;

-- Encuentra una competición por el número de eliminatorias
SELECT COMPETITION.NAME, NUM
FROM 
(
SELECT MATCH_PAIR.COMPETITION, COUNT(*) NUM  
FROM MATCH_PAIR 
GROUP BY MATCH_PAIR.COMPETITION
HAVING COUNT(*) = 2
) A JOIN COMPETITION ON A.COMPETITION = COMPETITION.ID 


SELECT MATCH_PAIR.COMPETITION, MATCH_PAIR.PHASE, COUNT(*) NUM 
FROM MATCH_PAIR 
WHERE MATCH_PAIR.PHASE = 'Semi-Finals'
GROUP BY MATCH_PAIR.COMPETITION, MATCH_PAIR.PHASE


SELECT COMPETITION.NAME, COMPETITION.SEASON, A.PHASE
FROM
(
SELECT MATCH_PAIR.COMPETITION, MATCH_PAIR.PHASE, COUNT(*) NUM 
FROM MATCH_PAIR 
WHERE MATCH_PAIR.PHASE = 'Semi-Finals'
GROUP BY MATCH_PAIR.COMPETITION, MATCH_PAIR.PHASE
HAVING COUNT(*) = 1
) A JOIN COMPETITION ON A.COMPETITION = COMPETITION.ID

SELECT COMPETITION.NAME, COMPETITION.SEASON, A.PHASE
FROM
(
SELECT MATCH_PAIR.COMPETITION, MATCH_PAIR.PHASE, COUNT(*) NUM 
FROM MATCH_PAIR 
WHERE MATCH_PAIR.PHASE = 'Quarter-Finals'
GROUP BY MATCH_PAIR.COMPETITION, MATCH_PAIR.PHASE
HAVING COUNT(*) < 4
) A JOIN COMPETITION ON A.COMPETITION = COMPETITION.ID

-- Número de equipos de cada pais en competiciones europeas
SELECT COUNTRY, COUNT(*) NUM  
FROM TEAM
GROUP BY COUNTRY
ORDER BY NUM DESC;


SELECT SEASON, START, COUNTRY, COUNT(*) NUM 
FROM
(
SELECT SEASON, START, T1.COUNTRY COUNTRY
FROM 
(MATCH_PAIR JOIN COMPETITION ON COMPETITION.ID = MATCH_PAIR.COMPETITION)
JOIN TEAM T1 ON T1.ID = MATCH_PAIR.TEAM1
WHERE MATCH_PAIR.PHASE = 'Quarter-Finals'
UNION ALL
SELECT SEASON, START, T2.COUNTRY COUNTRY
FROM 
(MATCH_PAIR JOIN COMPETITION ON COMPETITION.ID = MATCH_PAIR.COMPETITION)
JOIN TEAM T2 ON T2.ID = MATCH_PAIR.TEAM2
WHERE MATCH_PAIR.PHASE = 'Quarter-Finals'
) AS SF
GROUP BY SEASON, COUNTRY, START
ORDER BY START ASC,NUM DESC;

SELECT *
FROM TEAM 
WHERE NAME = 'Juventus'

SELECT COUNTRY, START, 
(
SELECT SUM(NUM) 
FROM COUNTRY_POTENTIAL
WHERE COUNTRY = c.COUNTRY
AND START < y.START AND START > y.START -5
) NUM
FROM 
(
SELECT DISTINCT COUNTRY 
FROM COUNTRY_POTENTIAL
ORDER BY COUNTRY
) c,
(
SELECT DISTINCT START
FROM COUNTRY_POTENTIAL
ORDER BY START
) y

SELECT * 
FROM COUNTRY_POTENTIAL_CUMULATIVE
WHERE 

-- Partidos ganados por el que acaba elimnatoria en casa
SELECT ID, 1 , TEAM2
FROM MATCH_PAIR
WHERE TOTAL2 > TOTAL1

SELECT count(*)
FROM MATCH_PAIR
WHERE TOTAL2 > TOTAL1


-- Partidos ganados por el que empieza elimnatoria en casa
SELECT ID, 0 , TEAM1
FROM MATCH_PAIR
WHERE TOTAL1 > TOTAL2

SELECT count(*)
FROM MATCH_PAIR
WHERE TOTAL1 > TOTAL2



SELECT ID, 2,  
FROM MATCH_PAIR
WHERE TOTAL1 = TOTAL2


SELECT count(*)
FROM MATCH_PAIR
WHERE TOTAL1 = TOTAL2



-- Eliminatorias empatadas
SELECT TEAM2, MA.COMPETITION, PHASE, NUMTOFINAL 
FROM MATCH_PAIR MA JOIN PHASE PA 
ON MA.COMPETITION = PA.COMPETITION
AND MA.PHASE = PA.NAME
WHERE TOTAL1 = TOTAL2

SELECT MB.TEAM1,MB.TEAM2,MB.COMPETITION, MB.PHASE, PB.NUMTOFINAL
FROM 
(MATCH_PAIR MA JOIN PHASE PA 
ON MA.COMPETITION = PA.COMPETITION 
AND MA.PHASE = PA.NAME),
(MATCH_PAIR MB JOIN PHASE PB 
ON MB.COMPETITION = PB.COMPETITION 
AND MB.PHASE = PB.NAME) 
WHERE MA.COMPETITION = MB.COMPETITION
AND PB.NUMTOFINAL < PA.NUMTOFINAL
AND (MB.TEAM1 = MA.TEAM2 OR MB.TEAM2 = MA.TEAM2)
ORDER BY MB.COMPETITION, PB.NUMTOFINAL 


SELECT * FROM COMPETITION WHERE ID = 1