-- 1. Export team names to post-process with Google Refine

SELECT NAME,COUNTRY,ID,NAME NAME_DUP,COUNTRY COUNTRY_DUP 
FROM TEAM;


-- 2.
drop table TEAM_DEDUP;

CREATE TABLE TEAM_DEDUP (
		NAME VARCHAR(50) NOT NULL,
		COUNTRY VARCHAR(3),
		ID_DUP INTEGER NOT NULL,
		NAME_DUP VARCHAR(50) NOT NULL,
		COUNTRY_DUP VARCHAR(3)
);

