-- Set phase variable
UPDATE PHASE SET NUMTOFINAL = 0  WHERE NAME='Final';
UPDATE PHASE SET NUMTOFINAL = 1  WHERE NAME='Semi-Finals';
UPDATE PHASE SET NUMTOFINAL = 2  WHERE NAME='Quarter-Finals' OR NAME='Quarter Finals';
UPDATE PHASE SET NUMTOFINAL = 3  WHERE NAME='1/8 Finals';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualifying Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Intermediate Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualifying Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='First Qualifying Phase';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Second Qualifying Phase';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Third Qualifying Phase';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualifying Phase 1';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualifying Phase 2';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualifying Phase 3';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualification Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Preliminary Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='First Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Second Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Third Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Fourth Round';
UPDATE PHASE SET NUMTOFINAL = 4  WHERE NAME='Qualifying Phase';

-- TABLE FOR COUNTRY POTENTIAL
CREATE TABLE COUNTRY_POTENTIAL
(
season VARCHAR(10),
start INTEGER,
country VARCHAR(50),
num INTEGER
);

-- DROP TABLE COUNTRY_POTENTIAL_CUMULATIVE

CREATE TABLE COUNTRY_POTENTIAL_CUMULATIVE
(
start INTEGER,
country VARCHAR(50),
num INTEGER
);


-- DELETE 
DELETE FROM COUNTRY_POTENTIAL;

-- CALCULATE COUNTRY_POTENTIAL PER YEAR 
INSERT INTO COUNTRY_POTENTIAL
SELECT SEASON, START, COUNTRY, COUNT(*) NUM 
FROM
(
SELECT SEASON, START, T1.COUNTRY COUNTRY
FROM 
(MATCH_PAIR JOIN COMPETITION ON COMPETITION.ID = MATCH_PAIR.COMPETITION)
JOIN TEAM T1 ON T1.ID = MATCH_PAIR.TEAM1
WHERE MATCH_PAIR.PHASE = 'Quarter-Finals'
UNION ALL
SELECT SEASON, START, T2.COUNTRY COUNTRY
FROM 
(MATCH_PAIR JOIN COMPETITION ON COMPETITION.ID = MATCH_PAIR.COMPETITION)
JOIN TEAM T2 ON T2.ID = MATCH_PAIR.TEAM2
WHERE MATCH_PAIR.PHASE = 'Quarter-Finals'
) AS SF
GROUP BY SEASON, COUNTRY, START
ORDER BY START ASC,NUM DESC;

-- CALCULATE COUNTRY POTENTIAL ACUMULATED BY LAST 5 YEARS
INSERT INTO COUNTRY_POTENTIAL_CUMULATIVE
SELECT START, COUNTRY,  
(
SELECT SUM(NUM) 
FROM COUNTRY_POTENTIAL
WHERE COUNTRY = c.COUNTRY
AND START < y.START AND START > y.START -5
) NUM
FROM 
(
SELECT DISTINCT COUNTRY 
FROM COUNTRY_POTENTIAL
ORDER BY COUNTRY
) c,
(
SELECT DISTINCT START
FROM COUNTRY_POTENTIAL
ORDER BY START
) y
